version: '2'
services:
  postgres:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=credit_card_control
    ports:
      - "5432:5432"
    volumes:
      - /data:/var/lib/postgresql/data
